[build]
  publish   = "project"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to   = "/Workshop%20Lam%20Thuong%20Hieu.html"
  status = 301

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
